language: php

php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - php -dmemory_limit=-1 composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs src --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml
  - vendor/bin/codecept run --coverage-xml

after_success:
  - vendor/bin/php-coveralls
